name             = Crypt-SaltedHash
main_module      = lib/Crypt/SaltedHash.pm
author           = Robert Rothenberg <perl@rhizomnic.com>
license          = Perl_5
copyright_holder = Sascha Kiefer
copyright_year   = 2005-2006, 2010, 2013, 2026

version = 0.10

[@Git]
tag_format = %v

[@Basic]
[MetaJSON]

[MetaResources]
bugtracker.web    = http://rt.cpan.org/Public/Dist/Display.html?Name=Crypt-SaltedHash

; If you have a repository...
repository.url    = git://github.com/robrwo/perl-Crypt-SaltedHash.git
repository.web    = https://github.com/robrwo/perl-Crypt-SaltedHash
repository.type   = git


[Prereqs]
Crypt::SysRandom           = 0
Digest                     = 0
MIME::Base64               = 0
POSIX                      = 0

[Prereqs / TestRequires]
Test::More                 = 0
Test::Fatal                = 0
